### ISSUE TITLE
[REQ] investigate macOS support

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#104]
### What kind of request is this?

None

### What is your request or suggestion?

publish darwin binaries as part of release

**Comment by sozercan** [comment]
@alexellis we use goreleaser for release so it's all baked in. Next release will automatically will contain both arch for linux and darwin.

I am not sure if copa had any new features to cut a v0.3.0 yet. I can update the issue once we are cutting it.

**Comment by alexellis** [comment]
Is there a chance you can cut a release for this now, so that we can get the PR right the first time, without having to go back and update / add extra URLs? The app was originally requested by @derdanne.
