### ISSUE TITLE
[REQ] GitHub Action for copa

### ISSUE THREAD

**Issue by salaxander** [project-copacetic/copacetic#12]
### What kind of request is this?

New feature

### What is your request or suggestion?

We should design a GitHub action to utilize copa. I think that would live in a separate repo in the same org

**Comment by reetasingh** [comment]
@salaxander can i work on this issue?

**Comment by salaxander** [comment]
Hey @reetasingh! I think we need to talk a little bit more on the design of this before we're ready to start work on it, but I will absolutely keep you posted!

**Comment by reetasingh** [comment]
> Hey @reetasingh! I think we need to talk a little bit more on the design of this before we're ready to start work on it, but I will absolutely keep you posted!

Thanks for the update @salaxander , meanwhile I am also open to any other issue

**Comment by ritazh** [comment]
WIP https://github.com/project-copacetic/copa-action/pull/1

**Comment by sozercan** [comment]
Available now: https://github.com/marketplace/actions/copacetic-action

Opened #245 for docs update follow up
