### ISSUE TITLE
[REQ] Handle secure registries

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#196]
### What kind of request is this?

New feature

### What is your request or suggestion?

Handle secure registries in copa:
- if image exists locally already, skip pulling the image
- if pulling image, handle authentication: copa will need to know how to use the auth file locally to authenticate with the registry)

**Comment by cpuguy83** [comment]
Does it not already handle this?

https://github.com/project-copacetic/copacetic/blob/fe06e35d19a24c66b95035e6b6faa2636cf5c2b5/pkg/buildkit/buildkit.go#L72-L82
