### ISSUE TITLE
[REQ] flag to continue when there are errors

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#203]
### What kind of request is this?

New feature

### What is your request or suggestion?

today, we fail patching if any package fails to patch

if patching fails for a package for whatever reason, we might want to continue anyway to produce an image

**Comment by anubhav06** [comment]
If no one is working on this issue, then can I work on this? 
How about a flag named `--force-patching`?

**Comment by sozercan** [comment]
@anubhav06 Thanks! I will assign to you.

Just for context, I was thinking we can approach this in a few ways:

1. (this issue) Scenario: Teams wants to patch an image ASAP but there are failures for some reason, but it's better to have something than nothing. This is where the flag comes in for fast resolution.
For the flag, should we align with flags that already exists in other tools? For example, GH calls this `continue-on-error` and make has `--ignore-errors`. What do you think?

2. (#214) Scenario: There is a known failure for some reason. So teams just want to ignore that CVE/package in their CI instead of ignoring all errors. This is more documentation on how to create policy to create filters with scanner tooling.

**Comment by anubhav06** [comment]
1. Yes. I think if we align with the existing flags from tools that already exist, that would be a better option. Both of them sounds good to me. I'll proceed with `--ignore-errors` flag for now. Let me know if you want me to name it something else.
2. I'll update the documentation for that as well
