### ISSUE TITLE
[DOC] filtering vulns with trivy

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#214]
### What kind of documentation improvement is needed?

None

### What is the change that is needed?

document how to filter vulns using rego policy or ignore file
https://aquasecurity.github.io/trivy/v0.43/docs/configuration/filtering/

example from CI: https://github.com/project-copacetic/copacetic/blob/3e22d49509ef9ef16aeedccfcc050f4ad627ed92/.github/workflows/build.yml#L112-L126

**Comment by anubhav06** [comment]
on it

**Comment by anubhav06** [comment]
I've come up with this documentation: https://docs.google.com/document/d/1ZkV2fxmYY2z9EP7FJtNuAS6AF1Kkyg6QfFYJGd5gUng/edit?usp=sharing
Let me know what do you think about it.

**Comment by sozercan** [comment]
> Question: This needs to be added to the website docs or the github docs?

Website docs, all user-facing docs should be there.

We should assess docs in github if they need to be moved to website (seperate issue).

**Comment by sozercan** [comment]
> I've come up with this documentation: [docs.google.com/document/d/1ZkV2fxmYY2z9EP7FJtNuAS6AF1Kkyg6QfFYJGd5gUng/edit?usp=sharing](https://docs.google.com/document/d/1ZkV2fxmYY2z9EP7FJtNuAS6AF1Kkyg6QfFYJGd5gUng/edit?usp=sharing) Let me know what do you think about it.

Thanks! Please feel to open a PR for this.
