### ISSUE TITLE
[REQ] Copa Docker image

### ISSUE THREAD

**Issue by salaxander** [project-copacetic/copacetic#368]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

There has been a request to make Copa available as a container image. We could have a simple distroless image containing the binary.

**Comment by sozercan** [comment]
We have the copa-action image today. Ideally we should be able to reuse this https://github.com/orgs/project-copacetic/packages/container/package/copa-action

**Comment by sozercan** [comment]
Closing as we already have the copa-action image
