### ISSUE TITLE
[QUESTION] Fixing containers without package managers

### ISSUE THREAD

**Issue by AshkanRafiee** [project-copacetic/copacetic#383]
### What is your question?

I’m using minimal containers without package managers like apt installed. I’m wondering if Project Copacetic can add the package manager again to fix the vulnerabilities in these containers. Also, I would like to know if the package manager will be removed again after fixing the vulnerabilities.

**Comment by sozercan** [comment]
@AshkanRafiee yes! copa should work for containers that doesn't have package managers installed. It works with distroless containers today by using a tooling container, it will not install any package managers.

Hope that answers your question. I'll close this but please feel free to re-open if it didn't.
