### ISSUE TITLE
[DOC] mention distroless containers can be patched

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#390]
### What kind of documentation improvement is needed?

Missing information or guidance

### What is the change that is needed?

looks like we are not mentioning this in the website. we should add a bullet point for this

related #383 

### Are you willing to submit PRs to contribute to documentation?

- [ ] Yes, I am willing to implement it.

**Comment by ritazh** [comment]
+1

 > It works with distroless containers today by using a tooling container, it will not install any package managers.

Might also help to describe the steps needed for ^^
