### ISSUE TITLE
[REQ] Provide more meaningful error messages

### ISSUE THREAD

**Issue by toddysm** [project-copacetic/copacetic#396]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

Adding more user context to the error messages that Copa returns helps troubleshoot unattended use of the tool. For example, I made a mistake to call copa with wrong reference to the image using digest like this:
```
myrepo/myimage:sha:<digest>
```
And the returned error was:
```
level=error msg="unexpected: TagNameOnly did create Tagged ref"
Error: unexpected: TagNameOnly did create Tagged ref
```
The above error doesn't help the user to understand what the problem is and leaves her wondering. 

Providing full context how the tool is invoked and what part of the invocation was wrong would be much friendlier.

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by prakrit55** [comment]
hey @sozercan, I would like to give it a try

**Comment by prakrit55** [comment]
hello @toddysm, I think the since the ` sha:<digest>` yet not supported in copa, it has given the following error `Error: invalid reference format` and it seems okay for the format to be like that, although it depends on the opinions 

wdyt @sozercan

**Comment by prakrit55** [comment]
hello @sozercan  when I tried with  
`copa patch -r nginx.1.21.6.json -i library/nginx:sha256:2bcabc23b45489fb0885d69a06ba1d648aeda973fae7bb981bafbb884165e514`, its giving `Error: invalid reference format`. Is this an expected behavior ??

**Comment by ashnamehrotra** [comment]
Hi @prakrit55 the correct format would be `copa patch -r nginx.1.21.6.json -i library/nginx:1.21.6@sha256:2bcabc23b45489fb0885d69a06ba1d648aeda973fae7bb981bafbb884165e514`
