### ISSUE TITLE
CANCELED exporting to docker image format: Error: exit status 1

### ISSUE THREAD

**Issue by ajmal-yazdani** [project-copacetic/copacetic#404]
### Version of copa

V 0.5.1

### Expected Behavior

Patched container image should created successfully.

### Actual Behavior

I am following this YT video https://www.youtube.com/watch?v=DUt4wnKV4a8&t=5s  by @sozercan and running below commands:

$ pulling nginx:1.18.0 container image from DockerHub
sudo docker pull nginx:1.18.0

$ use trivy scan the nginx:1.18.0 container image saving the output to nginx.1.18.0.json
sudo trivy image --vuln-type os --ignore-unfixed -f json -o nginx.1.18.0.json nginx:1.18.0

$ use trivy to output the number of vulnerabilities in the nginx:1.18.0 container image
sudo trivy image --vuln-type os --ignore-unfixed nginx:1.18.0 | grep Total

$ use trivy to output the dpkg vulnerabilities in the nginx:1.18.0 container image
sudo trivy image --vuln-type os --ignore-unfixed nginx:1.18.0 | grep dpkg

$ verify the dpkg version in the nginx:1.18.0 container image
sudo docker run  nginx:1.18.0 dpkg --version

$ run buildkit in a container locally, we'll need it to run Copa
sudo docker run --detach --rm --privileged -p 127.0.0.1:8888:8888/tcp --name buildkitd --entrypoint buildkitd moby/buildkit:v0.11.6 --addr tcp://0.0.0.0:8888

$ confirm the buildkitd container is running
sudo docker ps

$ use copa to patch the nginx:1.18.0 container image outputting the patched container image to nginx:1.18.0-patched
copa patch -i docker.io/library/nginx:1.18.0 -r nginx.1.18.0.json -t 1.18.0-patched -a tcp://0.0.0.0:8888

The last steps giving me below error:

[+] Building 29.7s (6/6) FINISHED                                                                                                                              => CACHED docker-image://docker.io/library/nginx:1.18.0                                                                                                 0.1s
 => => resolve docker.io/library/nginx:1.18.0                                                                                                            0.1s
 => apt update                                                                                                                                           3.0s
 => sh -c apt install --no-install-recommends --allow-change-held-packages -y libc6 libgcrypt20 debian-archive-keyring dpkg libicu63 libssh2-1 libxpm4  22.7s
 => diff (apt update) -> (sh -c apt install --no-install-recommends --allow-change-held-packages -y libc6 libgcrypt20 debian-archive-keyring dpkg libic  0.1s
 => merge (docker-image://docker.io/library/nginx:1.18.0, diff (apt update) -> (sh -c apt install --no-install-recommends --allow-change-held-packages   0.0s
 **=> CANCELED exporting to docker image format**                                                                                                            3.7s
 => => exporting layers                                                                                                                                  3.6s
 => => exporting manifest sha256:d5c3b92f1c697cb3c834e013bb2c148c2ab8ac2730d033327b7bb399c0f3fc6d                                                        0.0s
 => => exporting config sha256:fc8ffb3e67699b44db8e5801f52b249e6c1a573d6bab86bf8f8f52fbac5ea6fc                                                          0.0s
 => => sending tarball                                                                                                                                   0.0s
**Error: exit status 1**
 

### Steps To Reproduce

On Ubuntu 22.04 OS: 

$ pulling nginx:1.18.0 container image from DockerHub
sudo docker pull nginx:1.18.0

$ use trivy scan the nginx:1.18.0 container image saving the output to nginx.1.18.0.json
sudo trivy image --vuln-type os --ignore-unfixed -f json -o nginx.1.18.0.json nginx:1.18.0

$ use trivy to output the number of vulnerabilities in the nginx:1.18.0 container image
sudo trivy image --vuln-type os --ignore-unfixed nginx:1.18.0 | grep Total

$ use trivy to output the dpkg vulnerabilities in the nginx:1.18.0 container image
sudo trivy image --vuln-type os --ignore-unfixed nginx:1.18.0 | grep dpkg

$ verify the dpkg version in the nginx:1.18.0 container image
sudo docker run  nginx:1.18.0 dpkg --version

$ run buildkit in a container locally, we'll need it to run Copa
sudo docker run --detach --rm --privileged -p 127.0.0.1:8888:8888/tcp --name buildkitd --entrypoint buildkitd moby/buildkit:v0.11.6 --addr tcp://0.0.0.0:8888

$ confirm the buildkitd container is running
sudo docker ps

$ use copa to patch the nginx:1.18.0 container image outputting the patched container image to nginx:1.18.0-patched
copa patch -i docker.io/library/nginx:1.18.0 -r nginx.1.18.0.json -t 1.18.0-patched -a tcp://0.0.0.0:8888

Error for above step:

INFO[0037] Validated package openssl version 1.1.1n-0+deb10u6 meets requested version 1.1.1n-0+deb10u6
[+] Building 0.0s (0/5)
 => docker-image://docker.io/library/nginx:1.18.0                                                                                                        0.0s
[+] Building 29.7s (6/6) FINISHED                                                                                                                              => CACHED docker-image://docker.io/library/nginx:1.18.0                                                                                                 0.1s
 => => resolve docker.io/library/nginx:1.18.0                                                                                                            0.1s
 => apt update                                                                                                                                           3.0s
 => sh -c apt install --no-install-recommends --allow-change-held-packages -y libc6 libgcrypt20 debian-archive-keyring dpkg libicu63 libssh2-1 libxpm4  22.7s
 => diff (apt update) -> (sh -c apt install --no-install-recommends --allow-change-held-packages -y libc6 libgcrypt20 debian-archive-keyring dpkg libic  0.1s
 => merge (docker-image://docker.io/library/nginx:1.18.0, diff (apt update) -> (sh -c apt install --no-install-recommends --allow-change-held-packages   0.0s
 **=> CANCELED exporting to docker image format**                                                                                                            3.7s
 => => exporting layers                                                                                                                                  3.6s
 => => exporting manifest sha256:d5c3b92f1c697cb3c834e013bb2c148c2ab8ac2730d033327b7bb399c0f3fc6d                                                        0.0s
 => => exporting config sha256:fc8ffb3e67699b44db8e5801f52b249e6c1a573d6bab86bf8f8f52fbac5ea6fc                                                          0.0s
 => => sending tarball                                                                                                                                   0.0s
**Error: exit status 1**

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by ajmal-yazdani** [comment]
@sozercan , please suggest?

**Comment by anubhav06** [comment]
I think I had a similar error some time back. 
You can try running buildkit in [other modes](https://project-copacetic.github.io/copacetic/website/quick-start#sample-steps), rather than "Buildkit over TCP". Maybe try the "buildkit in a container" example (refer the [docs](https://project-copacetic.github.io/copacetic/website/quick-start#sample-steps)). That seemed to have fixed the issue for my particular case.

**Comment by ajmal-yazdani** [comment]
> I think I had a similar error some time back. You can try running buildkit in [other modes](https://project-copacetic.github.io/copacetic/website/quick-start#sample-steps), rather than "Buildkit over TCP". Maybe try the "buildkit in a container" example (refer the [docs](https://project-copacetic.github.io/copacetic/website/quick-start#sample-steps)). That seemed to have fixed the issue for my particular case.

I tried to run below command to run Buildkit  without TCP:

sudo docker run --detach --rm --privileged --name buildkitd --entrypoint buildkitd "moby/buildkit:v0.12.0"

But when I tried to run below command, it's starts giving permission issue:

 copa patch -i docker.io/library/nginx:1.21.6 -r nginx.1.21.6.json -t 1.21.6-patched --addr docker-container://buildkitd



Error: failed to get status: rpc error: code = Unavailable desc = rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: command [docker exec -i buildkitd buildctl dial-stdio] has exited with exit status 1, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/buildkitd/json\": dial unix /var/run/docker.sock: connect: permission denied\n"

**Comment by anubhav06** [comment]
@ajmal-yazdani why run buildkit with sudo privileges when you can run without it? Probably that's the cause of the permission issue. In docs as well, it is shown to run without sudo privileges. 
Just do:
```
docker run --detach --rm --privileged --name buildkitd --entrypoint buildkitd "moby/buildkit:v0.12.0"
```
and:
```
copa patch -i docker.io/library/nginx:1.21.6 -r nginx.1.21.6.json -t 1.21.6-patched --addr docker-container://buildkitd
```

**Comment by ajmal-yazdani** [comment]
@anubhav06, I am using Azure Ubuntu VM and problem is I can't install homebrew with root user and at the same time I can't use `docker run` without `sudo`.

I am seeing only documentation to install `copa` using `brew' only.

What's your thoughts here?

**Comment by anubhav06** [comment]
oh 🙂 
then maybe try running `copa` also with sudo, since you are running docker with sudo

**Comment by ajmal-yazdani** [comment]
No Copa not running with sudo. Saying unknown command

**Comment by anubhav06** [comment]
huh :/
I'm no expert with Linux but you can try this:
`sudo -E env "PATH=$PATH" copa patch ....`
more details [here](https://stackoverflow.com/a/29400598)

**Comment by sozercan** [comment]
looks like this is duplicate of #452
