### ISSUE TITLE
[DOC] Copa pulling older libraries

### ISSUE THREAD

**Issue by toddysm** [project-copacetic/copacetic#406]
### Expected Behavior

Expected to get the latest libraries

### Actual Behavior

#6 exporting to client directory
#6 copying files 4.42kB done
#6 DONE 0.1s
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libgssapi-krb5-2 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libkrb5-3 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libkrb5support0 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package linux-libc-dev version 6.1.38-4 lower than required 6.1.55-1 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package openssl version 3.0.9-1 lower than required 3.0.11-1~deb12u2 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libc-bin version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libc-dev-bin version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libc6 version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libc6-dev version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libk5crypto3 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update"
time="2023-11-03T18:15:41Z" level=error msg="downloaded package libssl3 version 3.0.9-1 lower than required 3.0.11-1~deb12u2 for update"
Error: 11 errors occurred:
  * downloaded package libgssapi-krb5-2 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update
  * downloaded package libkrb5-3 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update
  * downloaded package libkrb5support0 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update
  * downloaded package linux-libc-dev version 6.1.38-4 lower than required 6.1.55-1 for update
  * downloaded package openssl version 3.0.9-1 lower than required 3.0.11-1~deb12u2 for update
  * downloaded package libc-bin version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update
  * downloaded package libc-dev-bin version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update
  * downloaded package libc6 version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update
  * downloaded package libc6-dev version 2.36-9+deb12u1 lower than required 2.36-9+deb12u3 for update
  * downloaded package libk5crypto3 version 1.20.1-2 lower than required 1.20.1-2+deb12u1 for update
  * downloaded package libssl3 version 3.0.9-1 lower than required 3.0.11-1~deb12u2 for update

Error patching image tsmacrkubeconna23demousw2.azurecr.io/toddysm/python:3.10 with copa
2023/11/03 18:15:41 Container failed during run: patch-with_copa. No retries remaining.
failed to run step ID: patch-with_copa: exit status 1

Run ID: cc16 failed after 1m27s. Error: failed during run, err: exit status 1

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
@toddysm make sure to have fresh scan results. these are usually due to stale results (basically trivy and package repo disagreement), you'll need to make sure to scan before patch every time.

**Comment by sozercan** [comment]
we should document this in FAQ since this might be somewhat common if scan results are stale or scanner's db is outdated.
