### ISSUE TITLE
[REQ] Patch Image from private repository (azurecr.io for my case)

### ISSUE THREAD

**Issue by rakotomandimby** [project-copacetic/copacetic#412]
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

I would like `copa` to be able to patch image from private repository so that I can patch my self-made images.
I check "I am willing to implement it", but have no idea on where to begin: if you would help, it would be nice.

### Are you willing to submit PRs to contribute to this feature request?

- [x] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
@rakotomandimby this should already work if you are authenticated today. can you confirm you are authenticated and don't have the images locally?
for local images, this is in progress with #230

**Comment by sozercan** [comment]
@rakotomandimby https://github.com/project-copacetic/copacetic/releases/tag/v0.6.0 is out with local images support. Keep in mind this requires [containerd image store](https://docs.docker.com/storage/containerd/#enable-containerd-image-store-on-docker-engine). 

Closing this issue as complete. Feel free to re-open if you are still seeing this.
