### ISSUE TITLE
Copa Failed on Unmet dependencies

### ISSUE THREAD

**Issue by Pankajsh947** [project-copacetic/copacetic#429]
### Expected Behavior

It should have fixed broken installs suggested or ignore packages that have unmet dependencies

### Actual Behavior

So first it got this warning regarding the apt CLI interface 
 
and then it tries to install some packages and it fails to do so because the packages have unmet dependencies.
 
It is being suggested by the APT package manager to run apt --fix-broken-install, but i guess copa is ignoring the same, don't know if this can be fixed or it is a copa limitation or something.

below are the logs - 

#2 apt update
--
491 | #2 27.42
492 | #2 27.42 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
493 | #2 27.42
494 | #2 27.45 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
495 | #2 27.47 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
496 | #2 27.48 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
497 | #2 27.53 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8780 kB]
498 | #2 27.65 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [6668 B]
499 | #2 27.65 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [105 kB]
500 | #2 28.95 Fetched 9143 kB in 2s (6024 kB/s)
501 | #2 28.95 Reading package lists...
502 | #2 29.76 Building dependency tree...
503 | #2 29.96 Reading state information...
504 | #2 29.98 17 packages can be upgraded. Run 'apt list --upgradable' to see them.
505 | #2 DONE 30.1s
506 |  
507 | #3 sh -c apt install --no-install-recommends --allow-change-held-packages -y libavcodec-dev libswscale-dev libtiffxx6 libswresample4 libtiff-dev openssl libavformat59 libavutil57 libpmix2 libssl3 libavcodec59 libavformat-dev libswscale6 libavutil-dev libpq5 libswresample-dev libtiff6 && apt clean -y
508 | #3 28.68
509 | #3 28.68 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
510 | #3 28.68
511 | #3 28.69 Reading package lists...
512 | #3 29.15 Building dependency tree...
513 | #3 29.26 Reading state information...
514 | #3 29.27 You might want to run 'apt --fix-broken install' to correct these.
515 | #3 29.27 The following packages have unmet dependencies:
516 | #3 29.34  libavcodec59 : Depends: libjxl0.7 (>= 0.7.0) but it is not going to be installed
517 | #3 29.34 E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
518 | #3 ERROR: process "sh -c apt install --no-install-recommends --allow-change-held-packages -y libavcodec-dev libswscale-dev libtiffxx6 libswresample4 libtiff-dev openssl libavformat59 libavutil57 libpmix2 libssl3 libavcodec59 libavformat-dev libswscale6 libavutil-dev libpq5 libswresample-dev libtiff6 && apt clean -y" did not complete successfully: exit code: 100

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
Closing feel free to re-open with repro steps
