### ISSUE TITLE
[QUESTION] <title>Using Azure Container Registry in place of docker.io

### ISSUE THREAD

**Issue by ofschnai** [project-copacetic/copacetic#468]
### What is your question?

Is it possible to use 'Azure Container Registry(ACR)' in place of docker.io ?  I want to scan the vulnerabilities in docker image stored in ACR using github actions and upload the patched images back to ACR. 
Please share the possiblity and with an example. 

Below is the action I am using to scan the images from ACR

![image](https://github.com/project-copacetic/copacetic/assets/121802270/09e5e9ae-7c44-4532-a4a0-31c43f0e7630)

When I try to use Trivy and copa for scanning and patching, I am getting below error-

![image](https://github.com/project-copacetic/copacetic/assets/121802270/4ef20174-7929-49e6-a816-6efb5a13b203)

Thanks!

**Comment by sozercan** [comment]
duplicate of #471
