### ISSUE TITLE
[REQ] Using Azure Container Registry inplace of of docker.io registry.

### ISSUE THREAD

**Issue by ofschnai** [project-copacetic/copacetic#471]
### What kind of request is this?

Improvement of existing experience

### What is your question?

Is it possible to use 'Azure Container Registry(ACR)' in place of docker.io ?  I want to scan the vulnerabilities in docker image stored in ACR using github actions and upload the patched images back to ACR. 
Please share the possiblity and with an example. 

Below is the action I am using to scan the images from ACR

![image](https://github.com/project-copacetic/copacetic/assets/121802270/09e5e9ae-7c44-4532-a4a0-31c43f0e7630)

When I try to use Trivy and copa for scanning and patching, I am getting below error-

![image](https://github.com/project-copacetic/copacetic/assets/121802270/4ef20174-7929-49e6-a816-6efb5a13b203)

Thanks!

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
@ofschnai yes this is possible today. make sure to authenticate with ACR, looks like this error is coming from Trivy though

**Comment by ofschnai** [comment]
Thanks for the reply. 
Yes I am using ACR login to authenticate. This is how my yaml looks like

![image](https://github.com/project-copacetic/copacetic/assets/121802270/1404684f-ef70-47ff-ab6e-8ab62abc81c7)

**Comment by ofschnai** [comment]
Ok. I fixed that trivy issue. But getting time out when trying to execute the copacetic action as below -

![image](https://github.com/project-copacetic/copacetic/assets/121802270/617f1b36-ce00-4046-a99a-eedd785ed7b6)

and getting below error -

![image](https://github.com/project-copacetic/copacetic/assets/121802270/aed1d20d-b233-461f-9d55-72aad15cd376)

**Comment by sozercan** [comment]
@ofschnai sounds like github actions needs access to the registry.

**Comment by ofschnai** [comment]
I tried using docker login before the run copa action but it didn't help. What can be the solution for this?

![image](https://github.com/project-copacetic/copacetic/assets/121802270/7f57aace-75f2-446c-a792-849b77a6f640)

**Comment by ofschnai** [comment]
Yes I am able to pull without copa. Below are the action and logs for the same. But still getting error in copa action

![image](https://github.com/project-copacetic/copacetic/assets/121802270/25d9b301-8004-4d26-9001-f5aaaf566480)

**Comment by sozercan** [comment]
@ofschnai thanks for the report! I did some digging and this is due to action not supporting buildx builders, so they cannot access credentials. Opened https://github.com/project-copacetic/copa-action/issues/32

In the meantime, you can use copa as a binary inside a github action. Example: https://github.com/sozercan/copa-test/blob/main/.github/workflows/patch.yaml#L42-L54
Here's a test run: https://github.com/sozercan/copa-test/actions/runs/7647473401

**Comment by ofschnai** [comment]
@sozercan  Thanks for the temporary solution! I tried with this solution and it is working fine.
Let me know once the github action is back in use,  will change the configuration.

**Comment by sozercan** [comment]
Glad to hear it's working now. I'll close this issue and we'll track this in https://github.com/project-copacetic/copa-action/issues/32
