### ISSUE TITLE
[DOC] update source policy docs for debian 12

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#473]
### What kind of documentation improvement is needed?

None

### What is the change that is needed?

https://project-copacetic.github.io/copacetic/website/faq#can-i-replace-the-package-repositories-in-the-image-with-my-own

> Tooling image for Debian-based images are docker.io/library/debian:11-slim ...

tooling image can be 11 or 12 (depends on the target image version)

### Are you willing to submit PRs to contribute to documentation?

- [ ] Yes, I am willing to implement it.

**Comment by MiahaCybersec** [comment]
Should this change apply to versioned docs as well? If so, which ones?
