### ISSUE TITLE
[REQ] upgrade all packages without scanner input

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#522]
### What kind of request is this?

New feature

### What is your request or suggestion?

- [x] #546

- [x] #547

- [x] #569

- [ ] #592. 
(This will be a follow up since it is not specific to upgrade all feature)

- [x] #593

- [x] Copa will not be able to provide any vex output since it doesn't have any info on CVEs associated with the package upgrades.

- [x] #594
- [x] #687

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
@ashnamehrotra this is a good issue to pick up too

**Comment by ashnamehrotra** [comment]
upgrade all feature complete, #592 will be follow up
