### ISSUE TITLE
[BUG] Copa patch error grafana/grafana-image-renderer

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#524]
### Version of copa

v0.6.0

### Expected Behavior

When patching grafana/grafana-image-renderer:3.4.0, copa gives following error:

`#5 9.964 Executing shared-mime-info-2.4-r0.trigger
#5 9.969 ERROR: shared-mime-info-2.4-r0.trigger: script exited with error 127
#5 9.969 Executing gdk-pixbuf-2.42.10-r6.trigger
#5 9.974 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.975 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.975 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.976 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.977 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.978 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.978 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.979 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.981 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.981 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.982 g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so: Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.983 Executing gtk-update-icon-cache-3.24.41-r0.trigger
#5 9.987 Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 9.989 Executing gtk+3.0-3.24.41-r0.trigger
#5 9.996 Error relocating /usr/lib/libgtk-3.so.0: g_assertion_message_cmpint: symbol not found
#5 9.997 Error relocating /usr/lib/libgtk-3.so.0: g_task_set_static_name: symbol not found
#5 9.998 Error relocating /usr/lib/libgtk-3.so.0: g_string_free_and_steal: symbol not found
#5 9.999 Error relocating /usr/lib/libgdk-3.so.0: g_string_free_and_steal: symbol not found
#5 10.00 Error relocating /usr/lib/libgdk_pixbuf-2.0.so.0: g_task_set_static_name: symbol not found
#5 10.00 ERROR: gtk+3.0-3.24.41-r0.trigger: script exited with error 127
#5 10.01 OK: 674 MiB in 223 packages
#5 DONE 12.3s
`

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
This is expected and known bad one due to usage of alpine `edge` repo. It runs with ignoreErrors in the CI.
