### ISSUE TITLE
[REQ] Support "distroless" Alpine Images

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#596]
### What kind of request is this?

None

### What is your request or suggestion?

https://github.com/project-copacetic/copacetic/blob/d648155f5424a9f4cb13acd7209195846791873b/pkg/pkgmgr/apk.go#L161

Turning copacetic TODO comments into issues from https://docs.google.com/spreadsheets/d/1XwNj1J6e2FrUhlqaIsV10l8_tgov7WodlkvpNZXYZMU/edit#gid=1386834576.

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by MiahaCybersec** [comment]
APKO images appear to be detected as `osType Wolfi` so this issue can't be worked on until issue #38 is closed.

**Comment by sozercan** [comment]
that's correct. This comment in the code is old and should be removed.

**Comment by MiahaCybersec** [comment]
After investigation, the Copa team has decided that Wolfi support will not be added due to how complex the implementation would have to be. Docs will be updated to indicate this and the issue will be closed out 🙂
