### ISSUE TITLE
[REQ] support other tools in installToolsCmd for rpm tooling image

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#651]
### What kind of request is this?

None

### What is your request or suggestion?

Would it be possible to support other tools (yum, microdnf etc) for installing busybox to our tooling image in rpm? Currently, we use [tdnf](https://github.com/project-copacetic/copacetic/blob/main/pkg/pkgmgr/rpm.go#L37), but if the user changes the tooling image via [source policies](https://project-copacetic.github.io/copacetic/website/faq#can-i-replace-the-package-repositories-in-the-image-with-my-own) there is a chance tdnf is not supported in that image.

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by Akash-Singh04** [comment]
Hey is this issue still open?If so,  I would like to work on it

**Comment by Akash-Singh04** [comment]
Let me know if any separate changes are to be made for this issue or if it is resolved from the above PR as stated in #652
