### ISSUE TITLE
[REQ] Implement a possibility to skip "installToolsCmd"

### ISSUE THREAD

**Issue by benjamin-richter** [project-copacetic/copacetic#652]
### What kind of request is this?

New feature

### What is your request or suggestion?

I checked the official fedora and UBI 9 image, and there are some differences if and how `busybox cpio dnf-utils` are installable. So it would be great to implement the possibility to skip the installation of the tools and just check if the needed binaries are available. 
This would also be a fix for issue #651 

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by Akash-Singh04** [comment]
Hey is this issue still open?If so,  I would like to work on it

**Comment by Akash-Singh04** [comment]
Let me know if this implementation works!

**Comment by sozercan** [comment]
@MiahaCybersec  @ashnamehrotra okay to close this now?

**Comment by ashnamehrotra** [comment]
closed in #741
