### ISSUE TITLE
[DOC] Update development tips SolveToDocker reference

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#671]
### What kind of documentation improvement is needed?

None

### What is the change that is needed?

The buildkit.SolveToDocker() function referenced [here](https://project-copacetic.github.io/copacetic/website/next/development-tips#verify-the-intermediate-stages-of-building-a-patched-image) was removed in #181. It would be helpful to update the documentation to include the function for users to use for debugging purposes.

### Are you willing to submit PRs to contribute to documentation?

- [ ] Yes, I am willing to implement it.

**Comment by shishir-11** [comment]
I'm confused on what changes in the documentation is required, does the function no longer work and another function needs to be mentioned , if it still works then is the current documentation not sufficient ?

**Comment by ashnamehrotra** [comment]
@shishir-11 The function was removed from the code in #181, however the documentation still references it. `buildkit.SolveToDocker` was copa's custom function. It would be helpful to document the function in copa's website so users can add it in to help with dev/testing as needed.

**Comment by shishir-11** [comment]
I'm unable to find the changes to the buildkit.go or test file in #181 ,please correct me if I'm looking in the wrong place. I'd also like to know why it was removed and if some other method to do a similar action was put in its place.

**Comment by ashnamehrotra** [comment]
@shishir-11 sorry, this was supposed to be #381 (line 185 before it got removed since it was unused)

**Comment by shishir-11** [comment]
please check it out and point out any mistakes I might have made, Thanks.
