### ISSUE TITLE
[REQ] add tests for azure linux 3

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#697]
### What kind of request is this?

Other

### What is your request or suggestion?

adding tests for azure linux 3 preview core and distroless images 

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by shishir-11** [comment]
I'm kind of new here and wanted to learn a bit more about this issue and what tests are needed. Can you point me to any previous PRs linked to this or other resources that might help .
