### ISSUE TITLE
[REQ] Use apt-get instead of apt

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#787]
### What kind of request is this?

None

### What is your request or suggestion?

Investigate using apt-get for more stability instead of apt for Debian patching.

### Are you willing to submit PRs to contribute to this feature request?

- [ ] Yes, I am willing to implement it.

**Comment by prakrit55** [comment]
hello @ashnamehrotra, I would like to give it a try, can you assign it to me
