### ISSUE TITLE
[DOC] update tagging guidelines with squashing patch layers feature

### ISSUE THREAD

**Issue by sozercan** [project-copacetic/copacetic#788]
### What kind of documentation improvement is needed?

Missing information or guidance

### What is the change that is needed?

https://project-copacetic.github.io/copacetic/website/best-practices

this document references using unmodified images, we should update to include the new squashing patch layers feature

### Are you willing to submit PRs to contribute to documentation?

- [ ] Yes, I am willing to implement it.

**Comment by ashnamehrotra** [comment]
closed in #801
