### ISSUE TITLE
[QUESTION] <title>

### ISSUE THREAD

**Issue by Fr1ezy** [project-copacetic/copacetic#828]
### What is your question?

My Docker image source is a private source. Why do I use the official Docker source when patching with Copa? Where can I change the Copa image source

**Comment by ashnamehrotra** [comment]
@Fr1ezy if you are authenticated to your source you can patch the private image using the full docker source in copa patch. For example, `copa patch -i name.azurecr.io/private-image:tag`

**Comment by sozercan** [comment]
Closing this since it was answered. Feel free to re-open if it does not answer your question. Thanks!
