### ISSUE TITLE
[BUG] Copa can not find latest packages

### ISSUE THREAD

**Issue by leoj-msft** [project-copacetic/copacetic#836]
### Version of copa

0.0.29260904

### Expected Behavior

Copacetic task in the Azure pipeline addresses the vulnerability issues and patches the container image with latest packages.

### Actual Behavior

Copa fails to download latest packages. 
![image](https://github.com/user-attachments/assets/cc11e201-0a0c-4aab-b2d8-f2b2b0c1dedc)

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment]
@leoj-msft please see https://project-copacetic.github.io/copacetic/website/faq#i-am-getting-downloaded-package--version--lower-than-required--for-update-error-when-trying-to-patch-an-image-what-does-this-mean for debugging this error
