### ISSUE TITLE
[BUG] Failed to patch the docker image 

### ISSUE THREAD

**Issue by v-pramogupta** [project-copacetic/copacetic#869]
### Version of copa

1.0.2

### Expected Behavior

Copa is able to identify the vulnerable packages in docker image during scan, but it enables to patch them. Copa should patch the vulnerable packages.

### Actual Behavior

Copa is enables to patch the vulnerable packages in docker image.  I am getting below error :

time="2024-12-05T11:17:15Z" level=error msg="downloaded package curl version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package curl-libs version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package expat version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package expat-libs version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package glib version 2.71.0-2.cm2 lower than required 2.71.0-3.cm2 for update"
time="2024-12-05T11:17:15Z" level=info msg="Validated package libarchive version 3.6.1-4.cm2 meets requested version 3.6.1-4.cm2"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package nghttp2 version 1.57.0-1.cm2 lower than required 1.57.0-2.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package python3 version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package python3-curses version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package python3-libs version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update"
Error: 9 errors occurred:
	* downloaded package curl version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update
	* downloaded package curl-libs version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update
	* downloaded package expat version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update
	* downloaded package expat-libs version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update
	* downloaded package glib version 2.71.0-2.cm2 lower than required 2.71.0-3.cm2 for update
	* downloaded package nghttp2 version 1.57.0-1.cm2 lower than required 1.57.0-2.cm2 for update
	* downloaded package python3 version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update
	* downloaded package python3-curses version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update
	* downloaded package python3-libs version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update

### Steps To Reproduce

I have a function app project for that we are using docker build to create image and scan and patch the image using Copa in azure devops pipeline. But Copa is enables to patch the image. 
I have tried the same stapes with the MS provided function app template project as well which have minimal steps in docker file for that also it failed to patch with same error.
Attached is the docker file of both of actual function app and sample. 

[Dockerfile.txt](https://github.com/user-attachments/files/18093583/Dockerfile.txt)
[SampleFunAppDockerFile.txt](https://github.com/user-attachments/files/18093609/SampleFunAppDockerFile.txt)

I have tried to patch the image in my local system as well in docker desktop, but it will with same. 

Error logs:  
time="2024-12-05T11:17:15Z" level=error msg="downloaded package curl version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package curl-libs version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package expat version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package expat-libs version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package glib version 2.71.0-2.cm2 lower than required 2.71.0-3.cm2 for update"
time="2024-12-05T11:17:15Z" level=info msg="Validated package libarchive version 3.6.1-4.cm2 meets requested version 3.6.1-4.cm2"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package nghttp2 version 1.57.0-1.cm2 lower than required 1.57.0-2.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package python3 version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package python3-curses version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update"
time="2024-12-05T11:17:15Z" level=error msg="downloaded package python3-libs version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update"
Error: 9 errors occurred:
	* downloaded package curl version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update
	* downloaded package curl-libs version 8.8.0-2.cm2 lower than required 8.8.0-3.cm2 for update
	* downloaded package expat version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update
	* downloaded package expat-libs version 2.6.3-1.cm2 lower than required 2.6.3-2.cm2 for update
	* downloaded package glib version 2.71.0-2.cm2 lower than required 2.71.0-3.cm2 for update
	* downloaded package nghttp2 version 1.57.0-1.cm2 lower than required 1.57.0-2.cm2 for update
	* downloaded package python3 version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update
	* downloaded package python3-curses version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update
	* downloaded package python3-libs version 3.9.19-6.cm2 lower than required 3.9.19-7.cm2 for update

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by ashnamehrotra** [comment]
@v-pramogupta this error usually indicates that the scanner reports or package repositories are not up to date. More details are in our FAQ on how to proceed with patching https://project-copacetic.github.io/copacetic/website/faq#i-am-getting-downloaded-package--version--lower-than-required--for-update-error-when-trying-to-patch-an-image-what-does-this-mean

**Comment by v-pramogupta** [comment]
I am able to fix it by using a diff image for build.  Thank you.
